### ISSUE TITLE
Access console while viewer running

### ISSUE THREAD

**Issue by arkoe** [enflow-nl/cast-viewer#1]
I have the Cast Viewer running on my RPi, however, I need to change the source of some config files. Because of the 'infinite loop' I can't close the chromium kiosk mode, and I also can't access to it via SSH (permission denied (publickey). What are my options here? Do I have to reinstall the whole thing, change the source of the cast viewer before installing it? Any way to close/pause the infinite loop of the viewer?

**Comment by mbardelmeijer** [comment]
You should generate a new private/public key pair.

If you replace the public key with your own @ https://github.com/enflow-nl/cast-viewer/blob/master/ansible/roles/system/files/id_rsa.pub before installing, and authenticate yourself with that private key, you can SSH in correctly!
